### ISSUE TITLE
Add support for customizing ZIM illustration

### ISSUE THREAD

**Issue by benoit74** [openzim/devdocs#32]
It is important to be able to customize the ZIM illustration. 

Two solutions could be available (same CLI argument):
- a local path
- an HTTP(s) URL

In both cases, the illustration must be resized to 48x48 before being used.

Illustrations in common bitmap formats (a least PNG and JPG) and SVG must be supported 

Note that the python-scraperlib already contains primitives needed for all this, so we should probably package something to more easily support this feature in all our scrapers with very little (or no) code

**Comment by josephlewis42** [comment]
@benoit74 right now the scraper can produce multiple ZIMs. If the user supplies a CLI argument or the image could it be used for all the produced files?

Put another way, do we expect each DevDocs document to have its own ZimFarm recipe rather than using a single recipe for all docs or does the URL/file path need to be parameterized somehow?

**Comment by benoit74** [comment]
> If the user supplies a CLI argument or the image could it be used for all the produced files?

This is indeed a problem.

> Put another way, do we expect each DevDocs document to have its own ZimFarm recipe rather than using a single recipe for all docs or does the URL/file path need to be parameterized somehow?

Currently I'm pretty sure we will create one recipe per DevDocs slug, because experience showed that having one "big" thing with too much automated things is just a pain.

See https://github.com/openzim/devdocs/issues/29#issuecomment-2390669070 which might be the solution (i.e. we might decide not to need this option to customize ZIM illustration).
