### ISSUE TITLE
Support per-document thumbnail images

### ISSUE THREAD

**Issue by josephlewis42** [openzim/devdocs#8]
Devdocs is able to show a documentation set's icon because it compiles them all into a sprite sheet that's referenced by CSS.

All the icons exist in their GitHub repository, but aren't available in the published artifacts. 

`fcc2zim` has functionality today that can fetch a git repo which we could consider repurposing to grab thumbnail icons for the produced ZIM: https://github.com/openzim/freecodecamp/blob/a1221073049895609d7712a8834474311535f0c1/scraper/src/fcc2zim/fetch.py#L12

**Comment by josephlewis42** [comment]
Duplicate of #29

**Comment by benoit74** [comment]
Oups, sorry for having missed this issue when creating the other one ^^
